export const SKELETON_ENEMY = {
    name: "Skeleton",
    img: "entity/enemy_class/skeleton/skeleton_images/skeleton.png",
    type: "monster",
    size: "l",
    hp: 55,
    atk: 7,
    def: 2,
    crit: 1,
    dodge: 0,
    aim: 2,
    essence: 1,
    canAttack: true,
    desc: "An undead mob that shambles forward relentlessly.",
};
