export const DOCTOR_ENEMY = {
    name: "Doctor",
    img: "entity/enemy_class/doctor/doctor_images/doctor.png",
    type: "mage",
    size: "m",
    levels: ["all"],
    hp: 44,
    atk: 12,
    def: 2,
    crit: 9,
    dodge: 4,
    aim: 7,
    exp: 19,
    desc: "A sinister caster who curses foes with unstable magic. Moderate power, tricky timing, and dangerous critical bursts make it a constant threat.",
};
