export const NECROMANCER_ENEMY = {
    name: "Necromancer",
    img: "entity/enemy_class/necromancer/necromancer_images/necromancer.png",
    type: "mage",
    size: "l",
    levels: ["all"],
    hp: 38,
    atk: 13,
    def: 2,
    crit: 8,
    dodge: 3,
    aim: 8,
    exp: 19,
    desc: "A death caster who fights from safety with sharp magic. Frail in close combat, but dangerous through sustained spell pressure.",
};
