export const PEASANT_ENEMY = {
    name: "peasant",
    img: "entity/enemy_class/peasant/peasant_images/peasant.png",
    type: "monster",
    size: "xl",
    hp: 30,
    atk: 10,
    def: 5,
    crit: 3,
    dodge: 3,
    aim: 3,
    essence: 1,
    canAttack: true,
    desc: "a peasant ",
};
