export const KNIGHT_ENEMY = {
    name: "Knight",
    img: "entity/enemy_class/knight/knight_images/knight.png",
    type: "warrior",
    size: "l",
    hp: 72,
    atk: 10,
    def: 7,
    crit: 3,
    dodge: 1,
    aim: 5,
    essence: 3,
    canAttack: true,
    desc: "A disciplined heavy fighter wrapped in steel. High defense and reliable stats make it a durable battlefield anchor.",
};
