export const GOLEM_ENEMY = {
    name: "golem",
    img: "entity/enemy_class/golem/golem_images/golem.png",
    type: "monster",
    size: "2xl",
    levels: ["all"],
    hp: 150,
    atk: 10,
    def: 5,
    crit: 3,
    dodge: 3,
    aim: 3,
    exp: 15,
    desc: "giant metal golem",
};
